### ISSUE TITLE
Avoid memory copying / heap allocation

### ISSUE THREAD

**Issue by lukejackson** [phaistos-networks/TANK-JavaClient#1]
Given Tank is targeting "very high performance" one suggestion would be to use ByteBuffers or an abstract over ByteBuffer to access the message key & payload.

This avoids the need to allocate a byte array on the heap, copy the data into it, and then garbage collect the byte array for every message received.

**Comment by rkrambovitis** [comment]
Thanks for your comments.
I'll start working on it asap.

**Comment by rkrambovitis** [comment]
Unfortunately my implementation using ByteBuffers is proving slower than the original implementation.
So for now I'm going to revert, and maybe give it a fresh attempt later.

The branch buffers would be the latest iteration, using direct allocated byte buffers for most things.

Thanks
